site_name: Tabletop Simulator API
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/TSIcon.png'
  favicon: 'img/Icon-Dice.png'
  custom_dir: 'theme'

extra_css:
  - css/theme.css
  - css/table.css
  - css/type_icons.css
  - css/i_icons.css
  - css/player_color_table.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "\u0020"

repo_name: 'GitHub Source'
repo_url: 'https://github.com/tts-community/Tabletop-Simulator-API'


extra:
  social:
    - type: 'reddit'
      link: 'https://www.reddit.com/r/tabletopsimulator/'
    - type: 'twitter'
      link: 'https://twitter.com/tabletopsim'
    - type: 'facebook'
      link: 'https://www.facebook.com/tabletopsimulator'
    - type: 'youtube'
      link: 'https://www.youtube.com/user/berserkgames'

nav:
  - 'Getting Started':
    - 'Introduction': index.md
    - 'Overview': overview.md
    - 'Atom': atom.md
    - 'External Editor API': external-editor-api.md
    - 'Learning Lua': learning-lua.md
    - 'System Console': system-console.md
    - 'Virtual Reality': virtual-reality.md
    - 'Changelog': changelog.md
  - 'Scripting API':
    - 'Introduction': scripting/introduction.md
    - 'Types': scripting/types.md
    - 'Base': scripting/base.md
    - 'Event': scripting/event.md
    - 'Game Component':
      - 'Grid': scripting/game-component/grid.md
      - 'Lighting': scripting/game-component/lighting.md
      - 'Music Player': scripting/game-component/music-scripting/game-component/player.md
      - 'Notes': scripting/game-component/notes.md
      - 'Player': scripting/game-component/player.md
      - 'Turns': scripting/game-component/turns.md
    - 'Game Object':
      - 'Object': scripting/game-object/object.md
      - 'Object Component': scripting/game-object/object-component.md
      - 'AssetBundle': scripting/game-object/assetbundle.md
      - 'Book': scripting/game-object/book.md
      - 'Browser': scripting/game-object/browser.md
      - 'Clock': scripting/game-object/clock.md
      - 'Counter': scripting/game-object/counter.md
      - 'RPGFigurine': scripting/game-object/rpg-figurine.md
      - 'Spawnable Objects': scripting/game-object/spawnable-objects.md
      - 'TextTool': scripting/game-object/text-tool.md
    - 'Scripting Component':
      - 'Color': scripting/scripting-component/color.md
      - 'Player Color': player-scripting/scripting-component/player-color.md
      - 'JSON': scripting/scripting-component/json.md
      - 'Physics': scripting/scripting-component/physics.md
      - 'Time': scripting/scripting-component/time.md
      - 'UI': scripting/scripting-component/ui.md
      - 'Vector': scripting/scripting-component/vector.md
      - 'Wait': scripting/scripting-component/wait.md
      - 'Web Request': scripting/scripting-component/web-request.md
  - 'UI API':
    - 'Introduction': ui/introduction.md
    - 'Attributes': ui/attributes.md
    - 'Basic Elements': ui/basic-elements.md
    - 'Input Elements': ui/input-elements.md
    - 'Layout/Grouping': ui/layout-grouping.md
    - 'Defaults': ui/defaults.md
